# Generated by Django 5.0.6 on 2024-07-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiexamen', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='updated',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
