# Generated by Django 5.0.6 on 2024-07-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiexamen', '0003_remove_tasks_updated_alter_tasks_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=20),
        ),
    ]
